### ISSUE TITLE
Exception in BaseChainerEstimator 

### ISSUE THREAD

**Issue by HiuNaoki** [lucidfrontier45/scikit-chainer#1]
Hi 

test code could not work ..

 File "/usr/local/lib/python2.7/site-packages/skchainer/**init**.py", line 11
    class BaseChainerEstimator(base.BaseEstimator, metaclass=ABCMeta):
                                                            ^
SyntaxError: invalid syntax

please help me..

**Comment by lucidfrontier45** [comment]
fixed in commit f3c3c7429b905c93ca1cecf0b657eabf105ef2a4
Uploaded to pypi as version 0.4.2.

Now you can upgrade by the following command. 

``` bash
$ pip install -U scikit-chainer
```

**Comment by HiuNaoki** [comment]
thank you !!!
